[package]
name = "soft-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softbuffer = "0.1.1"
winit = "0.27.5"
winit_input_helper = "0.13.0"
glam = "0.22.0"
anyhow = "1.0.66"
tobj = "3.2.3"
